import test from 'node:test';
import assert from 'node:assert/strict';
import {handle,makeTicket,readTicket} from '../src/worker.js';
const req=(path,init)=>new Request('https://api.example.test'+path,init);
test('unconfigured services fail closed',async()=>{assert.equal((await handle(req('/api/observations'),{})).status,503);assert.equal((await handle(req('/api/admin/missions'),{})).status,503);});
test('authorization and CORS block before database connection',async()=>{let connects=0;const connect=()=>{connects++;throw Error('should not connect');};const env={ADMIN_TOKEN:'test-only-secret',ALLOWED_ORIGIN:'https://site.example.test',HYPERDRIVE:{}};assert.equal((await handle(req('/api/admin/missions'),env,connect)).status,401);assert.equal((await handle(req('/api/observations',{headers:{Origin:'https://other.example.test'}}),env,connect)).status,403);assert.equal(connects,0);});
test('public filters return bounded pages with no shared caching',async()=>{const statements=[];let closed=false;const db={query:async(sql,args)=>{statements.push([sql,args]);return {rows:sql.includes('SELECT o.id')?[{id:'1'},{id:'2'}]:[]};},end:async()=>{closed=true;}};const r=await handle(req('/api/observations?limit=1'),{HYPERDRIVE:{}},async()=>db);const b=await r.json();assert.equal(b.data.length,1);assert.equal(b.nextCursor,'1');assert.equal(r.headers.get('Cache-Control'),'no-store');assert.equal(closed,true);assert.match(statements[1][0],/publication_status='approved'/);});
test('database errors never disclose credentials or raw exception',async()=>{const r=await handle(req('/api/observations'),{HYPERDRIVE:{}},async()=>{throw Error('secret-database-connection');});assert.equal(r.status,503);assert.ok(!(await r.text()).includes('secret-database'));});
test('signed review rejects tampering and expiration',async()=>{const key='test-only-signing-secret',payload={sha:'abc',expires:Date.now()+10000};const ticket=await makeTicket(payload,key);assert.deepEqual(await readTicket(ticket,key),payload);await assert.rejects(()=>readTicket(ticket+'0',key));await assert.rejects(()=>readTicket(ticket,'wrong'));await assert.rejects(()=>readTicket(awaitable(),key));function awaitable(){return 'invalid';}const expired=await makeTicket({...payload,expires:1},key);await assert.rejects(()=>readTicket(expired,key),/expired/);});
